package component:validation

/// An example world for the component to target.
interface validating {
  record proto-envelope-body {
      content-bytes: list<u8>,
      key-id: string,
      signature: string
  }
  validate: func(package-records: list<proto-envelope-body>) -> result<list<bool>>
}
world validation {
  export validating
}                
